---
name: macOS

on:
  push:
    branches: [ "api_for_textworld" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "api_for_textworld" ]
  schedule:
    - cron: '37 20 * * 3'
  workflow_dispatch:

jobs:
  test:
    name: Compile and test planner - ${{ matrix.os }} - Python ${{ matrix.python }}
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
        python: ['3.9', '3.10', '3.12', '3.13']
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Downward's Python API
        run: |
          pip install .

      - name: Test Downward's Python API
        run: |
          pip install -r tests/requirements.txt
          nosetests -sv tests/test_interface.py
...
