---
name: Ubuntu - Tests

on:
  push:
    branches: [ "api_for_textworld" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "api_for_textworld" ]
  schedule:
    - cron: '37 20 * * 3'
  workflow_dispatch:

jobs:
  compile:
    name: "${{ matrix.os }} | py${{ matrix.python }}"
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest]
        python: ['3.9', '3.10', '3.12', '3.13']
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          sudo apt-get -y install zlib1g-dev libgmp3-dev
          mkdir /home/runner/work/downward/lib

      - name: Install Downward's Python API
        run: |
          pip install .

      - name: Test Downward's Python API
        run: |
          pip install -r tests/requirements.txt
          nosetests -sv tests/test_interface.py
...
